/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/hdc-exp2 copy.vue')['default']
    CreatePackets: typeof import('./src/components/CreatePackets.vue')['default']
    DropGraph: typeof import('./src/components/DropGraph.vue')['default']
    EatGraph: typeof import('./src/components/EatGraph.vue')['default']
    EffimatchExp1: typeof import('./src/components/effimatch-exp1.vue')['default']
    EffimatchExp2: typeof import('./src/components/effimatch-exp2.vue')['default']
    EffimatchExp3: typeof import('./src/components/effimatch-exp3.vue')['default']
    EffimatchExp4: typeof import('./src/components/effimatch-exp4.vue')['default']
    EffimatchExp5: typeof import('./src/components/effimatch-exp5.vue')['default']
    EffimatchExp6: typeof import('./src/components/effimatch-exp6.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FlowGraph: typeof import('./src/components/FlowGraph.vue')['default']
    HdcExp1: typeof import('./src/components/hdc-exp1.vue')['default']
    HdcExp2: typeof import('./src/components/hdc-exp2.vue')['default']
    HdcExp3: typeof import('./src/components/hdc-exp3.vue')['default']
    HdcExp4: typeof import('./src/components/hdc-exp4.vue')['default']
    HistoryGraph: typeof import('./src/components/HistoryGraph.vue')['default']
    QueueGraph: typeof import('./src/components/QueueGraph.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SwitchCard: typeof import('./src/components/SwitchCard.vue')['default']
    SwitchList: typeof import('./src/components/SwitchList.vue')['default']
    TopoGraph: typeof import('./src/components/TopoGraph.vue')['default']
  }
}
